version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb  # Diretório de contexto para o build do contêiner Mariadb.
    env_file:
      - .env  # Arquivo de ambiente contendo variáveis para o contêiner.
    ports:
      - 3306:3306  # Mapeamento de porta do host para o contêiner.
    volumes:
      - mariadb:/var/lib/mysql  # Volume para persistir os dados do banco de dados.
    networks:
      - inception  # Conecta o contêiner à rede "inception".

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress  # Diretório de contexto para o build do contêiner WordPress.
      dockerfile: Dockerfile  # Arquivo Dockerfile específico para o build do WordPress.
    env_file:
      - .env  # Arquivo de ambiente contendo variáveis para o contêiner.
    volumes:
      - wordpress:/var/www/html  # Volume para persistir os arquivos do WordPress.
    networks:
      - inception  # Conecta o contêiner à rede "inception".
    depends_on:
      - mariadb  # Indica que o contêiner depende do contêiner "mariadb" para iniciar.

  nginx:
    container_name: nginx
    image: nginx
    restart: always  # Política de reinicialização do contêiner em caso de falha.
    build:
      context: ./requirements/nginx  # Diretório de contexto para o build do contêiner Nginx.
      dockerfile: Dockerfile  # Arquivo Dockerfile específico para o build do Nginx.
    networks:
      - inception  # Conecta o contêiner à rede "inception".
    ports:
      - 443:443  # Mapeamento de porta do host para o contêiner.
    env_file:
      - .env  # Arquivo de ambiente contendo variáveis para o contêiner.
    volumes:
      - wordpress:/var/www/html  # Volume compartilhado com o contêiner WordPress.
    depends_on:
      - wordpress  # Indica que o contêiner depende do contêiner "wordpress" para iniciar.

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/mcesar-d/data/mariadb  # Caminho no host para o volume do Mariadb.
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/mcesar-d/data/wordpress  # Caminho no host para o volume do WordPress.

networks:
  inception:
    external: true  # Cria uma rede externa chamada "inception" para conectar os contêineres.
